icons_format = " <span font_family='NotoSans Nerd Font'>{icon}</span> "

theme = "slick"
icons = "material-nf"

[[block]]
block = "github"
token = "b4411229441aed4164a89dd39bf4d130c11adae0"
hide = true

[[block]]
block = "focused_window"
format = "{window:11^11}"

[[block]]
block = "net"
format = "{signal_stength} {graph_down}{speed_down;K}{speed_up;K}"
format_alt = "{ssid} {frequency} on {interface}"

[[block]]
block = "custom"
command = "du -hs / 2>/dev/null | tr -d /"
interval = 600

[[block]]
block = "cpu"
format = "{barchart} {utilization}"
format_alt = "{freq}"
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_used_percents:2}"
clickable = false

[[block]]
block = "temperature"
chip = "*-isa-*"
format = "{avg}"

#[[block]]
#block = "sound"
#on_click = "pavucontrol"
#format = "{volume:2#110} {volume:2}"

[[block]]
block = "custom"
command = "/home/maxv/my_custom.sh"
format = "'{exit_code}' '{stdout}' '{stderr}'"
json = true

[[block]]
block = "music"
[[block.click]]
button = "up"
update = false

[[block]]
block = "sway_kbd"
[block.mappings]
"English (Workman)" = "EN"
"Russian" = "RU"

[[block]]
block = "time"
icons_format = " "
interval = 30
format = "%d/%m %R"
[[block.click]]
button = "left"
cmd = "kitty"
[[block.click]]
button = "right"
cmd = "kitty"
sync = true
update = false
