theme = "gruvbox"

[keys.normal]
X = "extend_line_above"
# "X" = ["extend_line_up", "extend_to_line_bounds"]
# C-f = [":new", ":insert-output lf-hx-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme gruvbox"]

[keys.normal.space]
i = ":toggle-option lsp.display-inlay-hints"

[editor]
completion-replace = true
color-modes = true

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = { newline = "all" }
characters = { newline = "⏎" }

[editor.indent-guides]
render = true
skip-levels = 1

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[editor.smart-tab]
enable = false
