icons_format = " <span font_family='NotoSans Nerd Font'>{icon}</span> "

theme = "slick"
icons = "material-nf"

[[block]]
block = "battery"
full_format = ""

#[[block]]
#block = "github"
#hide_if_total_is_zero = true
#format = "{total:1}"
#
#[[block]]
#block = "net"
#format = "{signal_strength} {graph_down}{speed_down;K}{speed_up;K}"
#format_alt = "{ip} {ssid} {frequency}"
#interval = 2
#
#[[block]]
#block = "disk_space"
#info_type = "available"
#alert_absolute = true
#unit = "GB"
#alert = 19.0
#format = "{icon} {available:2}"
#
#[[block]]
#block = "cpu"
#format = "{barchart} {utilization} {frequency}"
#interval = 1
#
#[[block]]
#block = "memory"
#format_mem = "{mem_used_percents:2}"
#clickable = false
#
#[[block]]
#block = "temperature"
#collapsed = false
#format = "{average}"
#chip = "*-isa-*"
#
##[[block]]
##block = "sound"
##on_click = "pavucontrol"
##format = "{volume:2#110} {volume:2}"
#
#[[block]]
#block = "music"
#max_width = 15
#buttons = ["play"]

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "{layout}"
[block.mappings]
"English (Workman)" = "EN"
"Russian (N/A)" = "RU"

[[block]]
icons_format = " "
block = "time"
interval = 30
format = "%d/%m %R"
