double_click_delay = 0

[icons]
# icons = "material-nf"
name = "material-nf"

# Minimalistic gruvbox-dark variant
# [theme]
# name = "native"
# [theme.overrides]
# idle_fg = "#ebdbb2"
# info_fg = "#458588"
# good_fg = "#8ec07c"
# warning_fg = "#fabd2f"
# critical_fg = "#fb4934"

# Slick
[theme]
# theme = "slick"
name = "slick"
[theme.overrides]
separator = "native"
alternating_tint_bg = "none"
alternating_tint_fg = "none"

[[block]]
block = "hueshift"
hue_shifter = "wl_gammarelay_rs"

[[block]]
block = "focused_window"
driver = "auto"
[block.format]
full = "$title.rot-str(23, 0.5)"
short = "$title.rot-str(13, 0.5)"

# [[block]]
# block = "weather"
# format = "$temp"
# autolocate = true
# [block.service]
# name = "metno"

[[block]]
block = "pacman"
hide_when_uptodate = true

[[block]]
block = "github"
hide_if_total_is_zero = true
interval = 60

[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
adapter_mac = "F0:42:1C:ED:0D:6D"
hide_disconnected = true
format = ""

[[block]]
block = "net"
device = "wlp3s0"
format_alt = "{$ssid $frequency.eng(3) |}$device"
[block.format]
full = "{$signal_strength|}$speed_down.eng(3,auto,K)$speed_up.eng(3,auto,K)"
short = "$signal_strength|"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = "$available"
[[block.click]]
button = "right"
update = true

[[block]]
block = "cpu"
format_alt = "$frequency.eng(3,auto, M) \\|$boost"
interval = 1
[block.format]
full = "$barchart $utilization"
short = "$utilization"

[[block]]
block = "memory"
format_mem = "$mem_used_percents.eng(1)"
clickable = false

[[block]]
block = "temperature"
collapsed = false
format = "$average|"
chip = "*-isa-*"
inputs = ["Core 0", "Core 1"]

[[block]]
block = "sound"
driver = "pulseaudio"
[block.format]
full = "$volume.bar(4) $volume|"
short = "$volume|"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "music"
# hide_when_empty = true
# [block.format]
# full = "$combo.rot-str(25, 0.5)$prev$play$next|"
# short = "$combo.rot-str(15, 0.5)$play|"

[[block]]
block = "time"
icons_format = ""
[block.format]
full = "%d/%m %R"
short = "%R"

[[block]]
block = "menu"
text = "\uf011"
[[block.items]]
display = " -&gt;   Sleep   &lt;-"
cmd = "systemctl suspend"
[[block.items]]
display = " -&gt; Power Off &lt;-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"
[[block.items]]
display = " -&gt;  Reboot   &lt;-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"
