[error_fullscreen_format]
full = " $full_error_message "
short = " $full_error_message.str(w:170, rot_interval:0.2) "

[icons]
icons = "material-nf"
[icons.overrides]
no_wifi = "\U000f05aa" # nf-md-wifi_off
bell-slash = "\U000f00a0" # nf-md-bell_sleep
degree = "\u00B0"

# [theme]
# theme = "slick"
# [theme.overrides]
# # separator = "native"
# alternating_tint_bg = "none"
# alternating_tint_fg = "none"

[theme]
theme = "native"
# [theme.overrides]
# separator = "/"

[[block]]
block = "backlight"
ddcci_sleep_multiplier = 0.1
minimum = 0
format = " $icon $brightness"
merge_with_next = true

[[block]]
block = "pacman"
signal = 1
interval = 3600
error_interval = 60
format_up_to_date = ""
error_format = ""
[[block.click]]
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs-$USER | bemenu -b -l20 -"

[[block]]
block = "github"
hide_if_total_is_zero = true
interval = 120
[[block.click]]
button = "left"
cmd = "xdg-open https://github.com/notifications"

[[block]]
block = "net"
device = "wlo"
interval = 2
format = " $icon $speed_down.eng(w:3,p:K)/s "
format_alt = " $icon {$signal_strength|?} {$frequency.eng(w:3) |}{$ssid |}via $device "
inactive_format = " ^icon_no_wifi "
merge_with_next = true

[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
format = " $icon {$battery_icon |}"
disconnected_format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "disk_space"
interval = 60
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available.eng(w:5,p:1) "
format_alt = " $icon $used.eng(w:5,p:1)/$total.eng(w:5,p:1) "

[[block]]
block = "cpu"
interval = 5
format = " $icon $utilization "
format_alt = " $icon $utilization.eng(w:5) $max_frequency.eng(w:3,prefix:M) "
merge_with_next = true

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1
merge_with_next = true

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon $mem_used.eng(w:1)/$mem_total "
merge_with_next = true

[[block]]
block = "temperature"
format = " $icon $average "
chip = "k10temp-pci-00c3"
good = 0
info = 100
warning = 100

# [[block]]
# block = "music"
# seek_step_secs = 2
# format = " \u2004$play $combo.str(max_w:10, rot_interval:0.5) |"
# [[block.click]]
# button = "left"
# action = "play_pause"
# [[block.click]]
# button = "right"
# action = "next"
# [[block.click]]
# button = "middle"
# action = "next_player"

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume |}"
device_kind = "sink"
step_width = 1
merge_with_next = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume |}"
device_kind = "source"
step_width = 1
[block.theme_overrides]
idle_fg = { link = "warning_fg" }
idle_bg = { link = "warning_bg" }
warning_fg = { link = "idle_fg" }
warning_bg = { link = "idle_bg" }
[[block.click]]
button = "left"
action = "toggle_mute"

# [[block]]
# block = "keyboard_layout"
# driver = "river"
# [block.mappings]
# "English (programmer Dvorak)" = "en"
# "Russian (N/A)" = "ru"

[[block]]
block = "custom"
if_command = 'ps aux | rg "\d river"'
command = "river-kbd-layout-watcher 'English (programmer Dvorak)' en 'Russian' ru"
error_format = ""
persistent = true

[[block]]
block = "custom"
if_command = 'ps aux | rg "\d Hyprland"'
command = "hyprland-kbd-layout.sh"
persistent = true

[[block]]
block = "weather"
autolocate = true
autolocate_interval = "once"
format = " $icon {$wind.eng(w:1)}m/s $temp "
# format_alt = " $icon (3h forecast) {$wind_forecast.eng(w:1)}m/s $temp_forecast "
[block.service]
name = "metno"
# forecast_hours = 3

[[block]]
block = "tea_timer"
format = " ^icon_time {[$minutes:$seconds] |}"
done_cmd = "notify-send 'Timer Finished'"
merge_with_next = true

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%a %d %R') "

[[block]]
block = "battery"
driver = "upower"
full_threshold = 100
format = " $icon $percentage {($time) |}"
charging_format = " $icon $percentage "
not_charging_format = ""
full_format = ""
